version: '3.9'

services:
  krakend:
    image: devopsfaith/krakend:2.2.1

    volumes:
      - ./keycloak-krakend.json:/etc/krakend/krakend.json
    ports:
      - 10000:8080
    networks:
      - null_signal

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./database.dev.env
    networks:
      - backend

  keycloak:
    container_name: local_keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_FEATURES:
        authorization
        token-exchange
        docker
        impersonation
        scripts
        upload-scripts
        web-authn
        client-policies
        dynamic-scopes
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak 
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kc
    entrypoint: /opt/keycloak/bin/kc.sh --config-file=/opt/keycloak/conf/keycloak.conf start-dev
    volumes:
      - keycloak_data:/opt/keycloak/conf
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: on-failure
    networks:
      - backend
      - null_signal
    depends_on:
      postgres:
        condition: service_started

networks:
  null_signal:
    external: true
  backend:
    name: backend
    driver: bridge

volumes:
  keycloak_data:
  postgres_data:
